// lib/practiceStyles.js
//
// "Practice styles" are per-visitor visual skins for the mock-test taking
// screen (the question card, header, options, progress bar). Unlike
// siteThemes.js (which reskins the whole site's green accent colour),
// these only apply inside a test session and are meant to be things a
// learner would actually want while grinding practice questions: a calmer
// palette, a paper-like exam feel, a dark mode for evening revision, etc.
//
// Each style is expressed as a flat map of CSS custom properties. They're
// applied by PracticeStyleProvider onto a wrapper div (see
// PracticeStyleContext.jsx), and consumed by the `.ps-*` utility classes
// in src/styles/practiceStyles.css. Nothing outside that wrapper is
// affected, and falling back to `classic-clean` reproduces today's
// look exactly (same colours the app already used before this feature).

export const DEFAULT_PRACTICE_STYLE_ID = 'classic-clean'

// `swatch` is just two colours used to render the little preview icon in
// the picker (no image assets needed — see PracticeStylePicker.jsx).
export const PRACTICE_STYLES = [
  {
    id: 'classic-clean',
    name: 'Classic Clean',
    description: 'The original look — crisp white card, soft shadow',
    swatch: ['#ffffff', '#16a34a'],
    vars: {
      '--ps-page-from': '#f9fafb',
      '--ps-page-to': '#f3f4f6',
      '--ps-card-bg': '#ffffff',
      '--ps-card-border': '#e5e7eb',
      '--ps-card-shadow': '0 20px 25px -5px rgb(0 0 0 / 0.08), 0 8px 10px -6px rgb(0 0 0 / 0.06)',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#1f2937',
      '--ps-muted': '#6b7280',
      '--ps-accent': '#16a34a',
      '--ps-accent-strong': '#15803d',
      '--ps-accent-contrast': '#ffffff',
      '--ps-badge-bg': '#dcfce7',
      '--ps-badge-text': '#15803d',
      '--ps-option-border': '#e5e7eb',
      '--ps-option-bg': '#ffffff',
      '--ps-option-hover-border': '#16a34a',
      '--ps-option-hover-bg': '#f0fdf4',
      '--ps-correct-bg': '#f0fdf4',
      '--ps-correct-border': '#22c55e',
      '--ps-incorrect-bg': '#fef2f2',
      '--ps-incorrect-border': '#ef4444',
      '--ps-progress-from': '#22c55e',
      '--ps-progress-to': '#16a34a',
      '--ps-radius': '1rem',
    },
  },
  {
    id: 'exam-paper',
    name: 'Exam Paper',
    description: 'Cream page, ink border, serif type — feels like the real test',
    swatch: ['#f6efdc', '#3f3626'],
    vars: {
      '--ps-page-from': '#efe7d3',
      '--ps-page-to': '#e6dcc2',
      '--ps-card-bg': '#f8f2e2',
      '--ps-card-border': '#3f3626',
      '--ps-card-shadow': '0 4px 0 0 #3f3626',
      '--ps-font': "'Georgia', 'Times New Roman', serif",
      '--ps-text': '#2b2415',
      '--ps-muted': '#6b5f45',
      '--ps-accent': '#5b4a2f',
      '--ps-accent-strong': '#3f3626',
      '--ps-accent-contrast': '#f8f2e2',
      '--ps-badge-bg': '#e6dcc2',
      '--ps-badge-text': '#3f3626',
      '--ps-option-border': '#c9bb96',
      '--ps-option-bg': '#f8f2e2',
      '--ps-option-hover-border': '#3f3626',
      '--ps-option-hover-bg': '#efe4c8',
      '--ps-correct-bg': '#e7edd6',
      '--ps-correct-border': '#5c7a3a',
      '--ps-incorrect-bg': '#f3ded6',
      '--ps-incorrect-border': '#9c3f2c',
      '--ps-progress-from': '#8a7a4c',
      '--ps-progress-to': '#3f3626',
      '--ps-radius': '0.375rem',
    },
  },
  {
    id: 'hi-vis-safety',
    name: 'Hi-Vis Site Safety',
    description: 'Bold amber on charcoal — construction-site energy',
    swatch: ['#1f2428', '#f59e0b'],
    vars: {
      '--ps-page-from': '#15181b',
      '--ps-page-to': '#1f2428',
      '--ps-card-bg': '#20262b',
      '--ps-card-border': '#f59e0b',
      '--ps-card-shadow': '0 20px 25px -5px rgb(0 0 0 / 0.4)',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#f3f4f6',
      '--ps-muted': '#a8adb3',
      '--ps-accent': '#f59e0b',
      '--ps-accent-strong': '#d97706',
      '--ps-accent-contrast': '#1f2428',
      '--ps-badge-bg': '#f59e0b',
      '--ps-badge-text': '#1f2428',
      '--ps-option-border': '#3a4249',
      '--ps-option-bg': '#282f35',
      '--ps-option-hover-border': '#f59e0b',
      '--ps-option-hover-bg': '#33291a',
      '--ps-correct-bg': '#1f2e1f',
      '--ps-correct-border': '#4ade80',
      '--ps-incorrect-bg': '#301c1c',
      '--ps-incorrect-border': '#f87171',
      '--ps-progress-from': '#fbbf24',
      '--ps-progress-to': '#f59e0b',
      '--ps-radius': '0.75rem',
    },
  },
  {
    id: 'dark-focus',
    name: 'Dark Focus',
    description: 'Near-black card, glowing indigo — easy on tired eyes',
    swatch: ['#0b0b12', '#6366f1'],
    vars: {
      '--ps-page-from': '#08080d',
      '--ps-page-to': '#0f0f18',
      '--ps-card-bg': '#12121c',
      '--ps-card-border': '#26263a',
      '--ps-card-shadow': '0 0 0 1px #26263a, 0 0 40px -10px #6366f1aa',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#e5e7f5',
      '--ps-muted': '#8d8da8',
      '--ps-accent': '#818cf8',
      '--ps-accent-strong': '#6366f1',
      '--ps-accent-contrast': '#0b0b12',
      '--ps-badge-bg': '#26264a',
      '--ps-badge-text': '#c7d2fe',
      '--ps-option-border': '#26263a',
      '--ps-option-bg': '#181826',
      '--ps-option-hover-border': '#6366f1',
      '--ps-option-hover-bg': '#1c1c33',
      '--ps-correct-bg': '#132018',
      '--ps-correct-border': '#4ade80',
      '--ps-incorrect-bg': '#241419',
      '--ps-incorrect-border': '#fb7185',
      '--ps-progress-from': '#818cf8',
      '--ps-progress-to': '#6366f1',
      '--ps-radius': '1rem',
    },
  },
  {
    id: 'ocean-calm',
    name: 'Ocean Calm',
    description: 'Pale blue and soft edges — calm, low-pressure practice',
    swatch: ['#eaf5ff', '#0284c7'],
    vars: {
      '--ps-page-from': '#f0f9ff',
      '--ps-page-to': '#e0f2fe',
      '--ps-card-bg': '#ffffff',
      '--ps-card-border': '#bae6fd',
      '--ps-card-shadow': '0 20px 25px -5px rgb(2 132 199 / 0.10)',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#0c3a52',
      '--ps-muted': '#5b7f92',
      '--ps-accent': '#0ea5e9',
      '--ps-accent-strong': '#0284c7',
      '--ps-accent-contrast': '#ffffff',
      '--ps-badge-bg': '#e0f2fe',
      '--ps-badge-text': '#0369a1',
      '--ps-option-border': '#dbeeff',
      '--ps-option-bg': '#f8fcff',
      '--ps-option-hover-border': '#0ea5e9',
      '--ps-option-hover-bg': '#eaf6ff',
      '--ps-correct-bg': '#f0fdf4',
      '--ps-correct-border': '#22c55e',
      '--ps-incorrect-bg': '#fef2f2',
      '--ps-incorrect-border': '#ef4444',
      '--ps-progress-from': '#38bdf8',
      '--ps-progress-to': '#0284c7',
      '--ps-radius': '1.25rem',
    },
  },
  {
    id: 'forest-focus',
    name: 'Forest Focus',
    description: 'Fresh greens — a natural, easy-on-the-eyes theme',
    swatch: ['#eefbf1', '#15803d'],
    vars: {
      '--ps-page-from': '#f0fdf4',
      '--ps-page-to': '#dcfce7',
      '--ps-card-bg': '#ffffff',
      '--ps-card-border': '#bbf7d0',
      '--ps-card-shadow': '0 20px 25px -5px rgb(21 128 61 / 0.10)',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#14321f',
      '--ps-muted': '#4f7a5c',
      '--ps-accent': '#22c55e',
      '--ps-accent-strong': '#15803d',
      '--ps-accent-contrast': '#ffffff',
      '--ps-badge-bg': '#dcfce7',
      '--ps-badge-text': '#15803d',
      '--ps-option-border': '#d3f3de',
      '--ps-option-bg': '#f7fdf9',
      '--ps-option-hover-border': '#22c55e',
      '--ps-option-hover-bg': '#eafbf0',
      '--ps-correct-bg': '#e7f9ec',
      '--ps-correct-border': '#22c55e',
      '--ps-incorrect-bg': '#fef2f2',
      '--ps-incorrect-border': '#ef4444',
      '--ps-progress-from': '#4ade80',
      '--ps-progress-to': '#15803d',
      '--ps-radius': '1.25rem',
    },
  },
  {
    id: 'sunset-warm',
    name: 'Sunset Warm',
    description: 'Warm oranges and soft pinks for an energising session',
    swatch: ['#fff1e6', '#ea580c'],
    vars: {
      '--ps-page-from': '#fff7ed',
      '--ps-page-to': '#ffedd5',
      '--ps-card-bg': '#ffffff',
      '--ps-card-border': '#fed7aa',
      '--ps-card-shadow': '0 20px 25px -5px rgb(234 88 12 / 0.10)',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#431407',
      '--ps-muted': '#9a6a4f',
      '--ps-accent': '#f97316',
      '--ps-accent-strong': '#ea580c',
      '--ps-accent-contrast': '#ffffff',
      '--ps-badge-bg': '#ffedd5',
      '--ps-badge-text': '#c2410c',
      '--ps-option-border': '#fde3cc',
      '--ps-option-bg': '#fffaf3',
      '--ps-option-hover-border': '#f97316',
      '--ps-option-hover-bg': '#fff1e0',
      '--ps-correct-bg': '#f0fdf4',
      '--ps-correct-border': '#22c55e',
      '--ps-incorrect-bg': '#fef2f2',
      '--ps-incorrect-border': '#ef4444',
      '--ps-progress-from': '#fb923c',
      '--ps-progress-to': '#ea580c',
      '--ps-radius': '1.25rem',
    },
  },
  {
    id: 'slate-professional',
    name: 'Slate Professional',
    description: 'Cool greys and blue-grey accents — minimal and businesslike',
    swatch: ['#f1f5f9', '#334155'],
    vars: {
      '--ps-page-from': '#f8fafc',
      '--ps-page-to': '#eef2f6',
      '--ps-card-bg': '#ffffff',
      '--ps-card-border': '#e2e8f0',
      '--ps-card-shadow': '0 20px 25px -5px rgb(15 23 42 / 0.08)',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#1e293b',
      '--ps-muted': '#64748b',
      '--ps-accent': '#475569',
      '--ps-accent-strong': '#334155',
      '--ps-accent-contrast': '#ffffff',
      '--ps-badge-bg': '#e2e8f0',
      '--ps-badge-text': '#334155',
      '--ps-option-border': '#e2e8f0',
      '--ps-option-bg': '#f8fafc',
      '--ps-option-hover-border': '#475569',
      '--ps-option-hover-bg': '#eef2f6',
      '--ps-correct-bg': '#f0fdf4',
      '--ps-correct-border': '#22c55e',
      '--ps-incorrect-bg': '#fef2f2',
      '--ps-incorrect-border': '#ef4444',
      '--ps-progress-from': '#64748b',
      '--ps-progress-to': '#334155',
      '--ps-radius': '0.75rem',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Bold black, white and yellow — maximum legibility',
    swatch: ['#ffffff', '#000000'],
    vars: {
      '--ps-page-from': '#ffffff',
      '--ps-page-to': '#f5f5f5',
      '--ps-card-bg': '#ffffff',
      '--ps-card-border': '#000000',
      '--ps-card-shadow': '0 6px 0 0 #000000',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#000000',
      '--ps-muted': '#1a1a1a',
      '--ps-accent': '#000000',
      '--ps-accent-strong': '#000000',
      '--ps-accent-contrast': '#facc15',
      '--ps-badge-bg': '#facc15',
      '--ps-badge-text': '#000000',
      '--ps-option-border': '#000000',
      '--ps-option-bg': '#ffffff',
      '--ps-option-hover-border': '#000000',
      '--ps-option-hover-bg': '#fef9c3',
      '--ps-correct-bg': '#dcfce7',
      '--ps-correct-border': '#000000',
      '--ps-incorrect-bg': '#fee2e2',
      '--ps-incorrect-border': '#000000',
      '--ps-progress-from': '#facc15',
      '--ps-progress-to': '#000000',
      '--ps-radius': '0.25rem',
    },
  },
  {
    id: 'rose-quartz',
    name: 'Rose Quartz',
    description: 'Soft blush pink with rounded, gentle styling',
    swatch: ['#fff0f5', '#db2777'],
    vars: {
      '--ps-page-from': '#fff1f6',
      '--ps-page-to': '#fce7f3',
      '--ps-card-bg': '#ffffff',
      '--ps-card-border': '#fbcfe8',
      '--ps-card-shadow': '0 20px 25px -5px rgb(219 39 119 / 0.10)',
      '--ps-font': "'Inter', ui-sans-serif, system-ui, sans-serif",
      '--ps-text': '#500724',
      '--ps-muted': '#9d5877',
      '--ps-accent': '#ec4899',
      '--ps-accent-strong': '#db2777',
      '--ps-accent-contrast': '#ffffff',
      '--ps-badge-bg': '#fce7f3',
      '--ps-badge-text': '#be185d',
      '--ps-option-border': '#fbdce9',
      '--ps-option-bg': '#fffafc',
      '--ps-option-hover-border': '#ec4899',
      '--ps-option-hover-bg': '#fdf0f6',
      '--ps-correct-bg': '#f0fdf4',
      '--ps-correct-border': '#22c55e',
      '--ps-incorrect-bg': '#fef2f2',
      '--ps-incorrect-border': '#ef4444',
      '--ps-progress-from': '#f472b6',
      '--ps-progress-to': '#db2777',
      '--ps-radius': '1.5rem',
    },
  },
]

export function getPracticeStyleById(id) {
  return PRACTICE_STYLES.find((s) => s.id === id) || PRACTICE_STYLES.find((s) => s.id === DEFAULT_PRACTICE_STYLE_ID)
}
